### PR TITLE
Update unit test configuration so Jest can run, parse components

### PR DESCRIPTION
**Pull request by wingmatt**
Update the unit testing config to the point where unit tests can be written as needed for other branches.

Progress on #13 without fully completing it.

### CODE REVIEW

**Comment by Evomatic** [comment]
I pulled your branch and tried on my end. From my understanding [here](https://github.com/wingmatt/blatherbrush-nextjs/issues/13), you are able to mock now but tests still fail because mocks are not finished? 

When i ran the test locally I was getting failing points due to the [module aliases](https://nextjs.org/docs/pages/building-your-application/configuring/absolute-imports-and-module-aliases) imports. Changing the first import to a relative path fixed the first error but then still fails due to more module alias imports 😮  
image

I am guessing these are the failing tests that haven't had the mocks built out yet?

**Review by Evomatic — COMMENTED** [review]
I pulled your branch and tried on my end. From my understanding [here](https://github.com/wingmatt/blatherbrush-nextjs/issues/13), you are able to mock now but tests still fail because mocks are not finished? 

When i ran the test locally I was getting failing points due to the [module aliases](https://nextjs.org/docs/pages/building-your-application/configuring/absolute-imports-and-module-aliases) imports. Changing the first import to a relative path fixed the first error but then still fails due to more module alias imports 😮  
image

I am guessing these are the failing tests that haven't had the mocks built out yet?

**Comment by Evomatic** [comment]
Although it may be extra work, might be a good idea to have all tests passing before merging? Merging a PR with failing tests (even if not serious) is scary! 😨

**Comment by wingmatt** [comment]
@Evomatic That's fair, thanks for pointing that out!

The failing test was one from when I was first testing out my initial implementations + Jest and isn't super relevant now, so I went ahead and removed it.

**Pull request merged**
